# .github/workflows/deploy.yml

name: Scheduled Helios Deployment

on:
  schedule:
    # This runs the workflow every 2 hours.
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    env:
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      RPC_URL: ${{ secrets.RPC_URL }}

    steps:
      - name: Checkout repository
        # This action checks out your repository code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Compile contracts
        run: npx hardhat compile

      - name: Run Scheduled Deployment Logic
        # This runs your script, which modifies deployments.json
        run: node scripts/run-scheduled-deployment.js

      - name: Commit and Push changes
        # This new step will commit deployments.json back to your repo
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          # Required: The commit message for the update
          commit_message: "chore: Update deployment logs"
          
          # Optional: The file pattern to commit.
          # We only want to commit changes to this specific file.
          file_pattern: deployments.json
          
          # Optional: The user name and email to use for the commit
          commit_user_name: GitHub Actions
          commit_user_email: actions@github.com