# .github/workflows/deploy.yml

name: Scheduled Helios Deployment

on:
  schedule:
    # Runs the workflow every 2 hours on the default branch.
    - cron: '0 */2 * * *'
  
  # Also allows manual runs from the Actions tab.
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    env:
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      RPC_URL: ${{ secrets.RPC_URL }}

    steps:
      - name: Checkout repository
        # This will check out the default branch (main).
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Compile contracts
        run: npx hardhat compile

      - name: Run Scheduled Deployment Logic
        run: node scripts/run-scheduled-deployment.js

      - name: Commit and Push deployment logs
        # This action commits deployments.json back to the main branch.
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(bot): Update deployment logs"
          file_pattern: deployments.json
          commit_user_name: GitHub Actions Bot
          commit_user_email: actions@github.com