# .github/workflows/deploy.yml

name: Scheduled Helios Deployment

on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    env:
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      RPC_URL: ${{ secrets.RPC_URL }}

    steps:
      - name: Checkout 'workflow' branch
        uses: actions/checkout@v4
        with:
          ref: 'workflow'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Compile contracts
        run: npx hardhat compile

      - name: Run Scheduled Deployment Logic
        run: node scripts/run-scheduled-deployment.js

      - name: Commit and Push deployment logs
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(bot): Update deployment logs"
          commit_user_name: GitHub Actions Bot
          commit_user_email: actions@github.com