# .github/workflows/deploy.yml

name: Scheduled Helios Deployment

on:
  # This schedule runs the workflow every 2 hours.
  schedule:
    - cron: '0 */2 * * *'
  
  # This allows you to run the workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    # **FIX:** Define environment variables at the job level.
    # This makes them available to all steps in this job.
    env:
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      RPC_URL: ${{ secrets.RPC_URL }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Compile contracts
        # This step will now have access to the secrets and will succeed.
        run: npx hardhat compile

      - name: Run Scheduled Deployment Logic
        # This script also has access to the secrets, as before.
        run: node scripts/run-scheduled-deployment.js