# .github/workflows/deploy.yml

name: Scheduled Helios Deployment

on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    env:
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      RPC_URL: ${{ secrets.RPC_URL }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Compile contracts
        run: npx hardhat compile

      - name: Run Scheduled Deployment Logic
        run: node scripts/run-scheduled-deployment.js

      - name: Commit and Push workflow.json
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add workflow.json
          # Only commit if there are changes
          git diff-index --quiet HEAD || git commit -m "chore(bot): Update workflow deployment logs"
          git push