# .github/workflows/deploy.yml

name: Scheduled Helios Deployment & Release

on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write # Required to create releases and push commits

    env:
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      RPC_URL: ${{ secrets.RPC_URL }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm install
          npm install undici # Install the HTTP client for the release script

      - name: Compile contracts
        run: npx hardhat compile

      - name: Run Scheduled Deployment Logic
        id: deployment
        run: node scripts/run-scheduled-deployment.js

      - name: Commit and Push workflow.json
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add workflow.json
          # Only commit if there are changes
          if ! git diff-index --quiet HEAD; then
            git commit -m "chore(bot): Update workflow deployment logs"
            git push
          else
            echo "No changes to workflow.json to commit."
          fi
      
      - name: Create GitHub Release
        # Run this step only if the deployment was successful
        if: success()
        run: node scripts/create-release.js